ElectionAutomationSystem/Models/Province.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectionAutomationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Province
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Province()
        {
            this.Districts = new HashSet<District>();
            this.Parties = new HashSet<Party>();
            this.Presidents = new HashSet<President>();
        }
    
        public int ProvinceId { get; set; }
        public string ProvinceName { get; set; }
        public Nullable<int> ElectionId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<District> Districts { get; set; }
        public virtual Election Election { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Party> Parties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<President> Presidents { get; set; }
    }
}

ElectionAutomationSystem/Controllers/ProvincesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ElectionAutomationSystem.Models;

namespace ElectionAutomationSystem.Controllers
{
    public class ProvincesController : Controller
    {
        private ElectionDatabaseEntities db = new ElectionDatabaseEntities();

        // GET: Provinces
        public ActionResult Index()
        {
            var provinces = db.Provinces.Include(p => p.Election);
            return View(provinces.ToList());
        }

        // GET: Provinces/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Province province = db.Provinces.Find(id);
            if (province == null)
            {
                return HttpNotFound();
            }
            return PartialView(province);
        }

        // GET: Provinces/Create
        public ActionResult Create()
        {
            ViewBag.ElectionId = new SelectList(db.Elections, "ElectionId", "ElectionTitle");
            return PartialView();
        }

        // POST: Provinces/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProvinceId,ProvinceName,ElectionId")] Province province)
        {
            if (ModelState.IsValid)
            {
                db.Provinces.Add(province);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ElectionId = new SelectList(db.Elections, "ElectionId", "ElectionTitle", province.ElectionId);
            return PartialView(province);
        }

        // GET: Provinces/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Province province = db.Provinces.Find(id);
            if (province == null)
            {
                return HttpNotFound();
            }
            ViewBag.ElectionId = new SelectList(db.Elections, "ElectionId", "ElectionTitle", province.ElectionId);
            return PartialView(province);
        }

        // POST: Provinces/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProvinceId,ProvinceName,ElectionId")] Province province)
        {
            if (ModelState.IsValid)
            {
                db.Entry(province).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ElectionId = new SelectList(db.Elections, "ElectionId", "ElectionTitle", province.ElectionId);
            return PartialView(province);
        }

        // GET: Provinces/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Province province = db.Provinces.Find(id);
            if (province == null)
            {
                return HttpNotFound();
            }
            return PartialView(province);
        }

        // POST: Provinces/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Province province = db.Provinces.Find(id);
            db.Provinces.Remove(province);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ElectionAutomationSystem/Views/Provinces/Create.cshtml
@model ElectionAutomationSystem.Models.Province

@{
    ViewBag.Title = "Create";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Province</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ProvinceName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProvinceName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProvinceName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ElectionId, "ElectionTitle", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ElectionId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ElectionId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
                <button class="btn btn-danger" type="button" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
}

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

ElectionAutomationSystem/Views/Provinces/Delete.cshtml
@model ElectionAutomationSystem.Models.Province

@{
    ViewBag.Title = "Delete";
}

<div>
    <h4>Province</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProvinceName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProvinceName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Election.ElectionTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Election.ElectionTitle)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-primary" />
            <button class="btn btn-danger" type="button" data-dismiss="modal">Cancel</button>
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-primary" />
                <button class="btn btn-danger" type="button" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    }
</div>

ElectionAutomationSystem/Views/Provinces/Details.cshtml
@model ElectionAutomationSystem.Models.Province

@{
    ViewBag.Title = "Details";
}

<div>
    <h4>Province</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProvinceName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProvinceName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Election.ElectionTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Election.ElectionTitle)
        </dd>

    </dl>
</div>
<p>
    <button class="btn btn-danger" type="button" data-dismiss="modal">Back</button>
</p>

ElectionAutomationSystem/Views/Provinces/Edit.cshtml
@model ElectionAutomationSystem.Models.Province

@{
    ViewBag.Title = "Edit";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Province</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ProvinceId)

        <div class="form-group">
            @Html.LabelFor(model => model.ProvinceName, "ProvinceName", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProvinceName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProvinceName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ElectionId, "ElectionTitle", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ElectionId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ElectionId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
                <button class="btn btn-danger" type="button" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
}

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

ElectionAutomationSystem/Views/Provinces/Index.cshtml
@model IEnumerable<ElectionAutomationSystem.Models.Province>

@{
    ViewBag.Title = "Index";
}

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Provinces - Election Automation System</title>
    <!-- Bootstrap core CSS-->
    <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom fonts for this template-->
    <link href="~/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <!-- Page level plugin CSS-->
    <link href="~/vendor/datatables/dataTables.bootstrap4.css" rel="stylesheet">
    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin.css" rel="stylesheet">
</head>

<ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="@(Url.Action("Index", "Home"))">Election Automation System</a></li>
    <li class="breadcrumb-item"><a href="#">Regions</a></li>
    <li class="breadcrumb-item"><a href="@(Url.Action("Index", "Provinces"))">Provinces</a></li>
    <li class="breadcrumb-item active">Index</li>
</ol>

<p>
    <a class="navbar-brand" data-toggle="modal" data-target="#popupId" onclick="showCreate('Provinces')"><button type="button" class="btn btn-primary">Create New</button></a>
</p>

<!-- Example DataTables Card-->
<div class="card mb-3">
    <div class="card-header">
        <i class="fa fa-table"></i> Provinces
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Province Name</th>
                        <th>Election Title</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.ProvinceName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Election.ElectionTitle)
                            </td>
                            <td>
                                <a class="navbar-brand" data-toggle="modal" data-target="#popupId" onclick="showEdit('Provinces',@item.ProvinceId)"><button type="button" class="btn btn-info">Edit</button></a>
                                <a class="navbar-brand" data-toggle="modal" data-target="#popupId" onclick="showDetails('Provinces',@item.ProvinceId)"><button type="button" class="btn btn-warning">Details</button></a>
                                <a class="navbar-brand" data-toggle="modal" data-target="#popupId" onclick="showDelete('Provinces',@item.ProvinceId)"><button type="button" class="btn btn-danger">Delete </button></a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
</div>

<!-- Bootstrap core JavaScript-->
<script src="~/vendor/jquery/jquery.min.js"></script>
<script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- Core plugin JavaScript-->
<script src="~/vendor/jquery-easing/jquery.easing.min.js"></script>
<!-- Page level plugin JavaScript-->
<script src="~/vendor/datatables/jquery.dataTables.js"></script>
<script src="~/vendor/datatables/dataTables.bootstrap4.js"></script>
<!-- Custom scripts for all pages-->
<script src="~/js/sb-admin.min.js"></script>
<!-- Custom scripts for this page-->
<script src="~/js/sb-admin-datatables.min.js"></script>