ElectionAutomationSystem/Models/BallotBox.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectionAutomationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BallotBox
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BallotBox()
        {
            this.Votes = new HashSet<Vote>();
        }
    
        public int BallotBoxId { get; set; }
        public Nullable<int> BallotBoxNumber { get; set; }
        public Nullable<int> NeighbourhoodId { get; set; }
        public Nullable<int> VoterCount { get; set; }
    
        public virtual Neighbourhood Neighbourhood { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vote> Votes { get; set; }
    }
}

ElectionAutomationSystem/Controllers/BallotBoxesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ElectionAutomationSystem.Models;

namespace ElectionAutomationSystem.Controllers
{
    public class BallotBoxesController : Controller
    {
        private ElectionDatabaseEntities db = new ElectionDatabaseEntities();

        // GET: BallotBoxes
        public ActionResult Index()
        {
            var ballotBoxes = db.BallotBoxes.Include(b => b.Neighbourhood);
            return View(ballotBoxes.ToList());
        }

        // GET: BallotBoxes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BallotBox ballotBox = db.BallotBoxes.Find(id);
            if (ballotBox == null)
            {
                return HttpNotFound();
            }
            return PartialView(ballotBox);
        }

        // GET: BallotBoxes/Create
        public ActionResult Create()
        {
            ViewBag.NeighbourhoodId = new SelectList(db.Neighbourhoods, "NeighbourhoodId", "NeighbourhoodName");
            return PartialView();
        }

        // POST: BallotBoxes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BallotBoxId,BallotBoxNumber,NeighbourhoodId,VoterCount")] BallotBox ballotBox)
        {
            if (ModelState.IsValid)
            {
                db.BallotBoxes.Add(ballotBox);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.NeighbourhoodId = new SelectList(db.Neighbourhoods, "NeighbourhoodId", "NeighbourhoodName", ballotBox.NeighbourhoodId);
            return PartialView(ballotBox);
        }

        // GET: BallotBoxes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BallotBox ballotBox = db.BallotBoxes.Find(id);
            if (ballotBox == null)
            {
                return HttpNotFound();
            }
            ViewBag.NeighbourhoodId = new SelectList(db.Neighbourhoods, "NeighbourhoodId", "NeighbourhoodName", ballotBox.NeighbourhoodId);
            return PartialView(ballotBox);
        }

        // POST: BallotBoxes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BallotBoxId,BallotBoxNumber,NeighbourhoodId,VoterCount")] BallotBox ballotBox)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ballotBox).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.NeighbourhoodId = new SelectList(db.Neighbourhoods, "NeighbourhoodId", "NeighbourhoodName", ballotBox.NeighbourhoodId);
            return PartialView(ballotBox);
        }

        // GET: BallotBoxes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BallotBox ballotBox = db.BallotBoxes.Find(id);
            if (ballotBox == null)
            {
                return HttpNotFound();
            }
            return PartialView(ballotBox);
        }

        // POST: BallotBoxes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BallotBox ballotBox = db.BallotBoxes.Find(id);
            db.BallotBoxes.Remove(ballotBox);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ElectionAutomationSystem/Views/BallotBoxes/Create.cshtml
@model ElectionAutomationSystem.Models.BallotBox

@{
    ViewBag.Title = "Create";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>BallotBox</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.BallotBoxNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BallotBoxNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BallotBoxNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NeighbourhoodId, "NeighbourhoodName", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("NeighbourhoodId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.NeighbourhoodId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VoterCount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VoterCount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VoterCount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
                <button class="btn btn-danger" type="button" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
}

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

ElectionAutomationSystem/Views/BallotBoxes/Delete.cshtml
@model ElectionAutomationSystem.Models.BallotBox

@{
    ViewBag.Title = "Delete";
}
<div>
    <h4>BallotBox</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BallotBoxNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BallotBoxNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VoterCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VoterCount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Neighbourhood.NeighbourhoodName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Neighbourhood.NeighbourhoodName)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-primary" />
            <button class="btn btn-danger" type="button" data-dismiss="modal">Cancel</button>
        </div>
    }
</div>

ElectionAutomationSystem/Views/BallotBoxes/Details.cshtml
@model ElectionAutomationSystem.Models.BallotBox

@{
    ViewBag.Title = "Details";
}

<div>
    <h4>BallotBox</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BallotBoxNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BallotBoxNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VoterCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VoterCount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Neighbourhood.NeighbourhoodName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Neighbourhood.NeighbourhoodName)
        </dd>

    </dl>
</div>
<p>
    <button class="btn btn-danger" type="button" data-dismiss="modal">Back</button>
</p>

ElectionAutomationSystem/Views/BallotBoxes/Edit.cshtml
@model ElectionAutomationSystem.Models.BallotBox

@{
    ViewBag.Title = "Edit";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>BallotBox</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.BallotBoxId)

        <div class="form-group">
            @Html.LabelFor(model => model.BallotBoxNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BallotBoxNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BallotBoxNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NeighbourhoodId, "NeighbourhoodName", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("NeighbourhoodId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.NeighbourhoodId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VoterCount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VoterCount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VoterCount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
                <button class="btn btn-danger" type="button" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
}

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

ElectionAutomationSystem/Views/BallotBoxes/Index.cshtml
@model IEnumerable<ElectionAutomationSystem.Models.BallotBox>

@{
    ViewBag.Title = "Index";
}
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Ballot Boxes - Election Automation System</title>
    <!-- Bootstrap core CSS-->
    <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom fonts for this template-->
    <link href="~/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <!-- Page level plugin CSS-->
    <link href="~/vendor/datatables/dataTables.bootstrap4.css" rel="stylesheet">
    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin.css" rel="stylesheet">
</head>

<ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="@(Url.Action("Index", "Home"))">Election Automation System</a></li>
    <li class="breadcrumb-item"><a href="#">Regions</a></li>
    <li class="breadcrumb-item"><a href="@(Url.Action("Index", "BallotBoxes"))">Ballot Boxes</a></li>
    <li class="breadcrumb-item active">Index</li>
</ol>

<p>
    <a class="navbar-brand" data-toggle="modal" data-target="#popupId" onclick="showCreate('BallotBoxes')"><button type="button" class="btn btn-primary">Create New</button></a>
</p>

<!-- Example DataTables Card-->
<div class="card mb-3">
    <div class="card-header">
        <i class="fa fa-table"></i> Ballot Boxes
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Ballot Box Number</th>
                        <th>Voter Count</th>
                        <th>Neighbourhood Name</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.BallotBoxNumber)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.VoterCount)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Neighbourhood.NeighbourhoodName)
                            </td>
                            <td>
                                <a class="navbar-brand" data-toggle="modal" data-target="#popupId" onclick="showEdit('BallotBoxes',@item.BallotBoxId)"><button type="button" class="btn btn-info">Edit</button></a>
                                <a class="navbar-brand" data-toggle="modal" data-target="#popupId" onclick="showDetails('BallotBoxes',@item.BallotBoxId)"><button type="button" class="btn btn-warning">Details</button></a>
                                <a class="navbar-brand" data-toggle="modal" data-target="#popupId" onclick="showDelete('BallotBoxes',@item.BallotBoxId)"><button type="button" class="btn btn-danger">Delete </button></a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
</div>

<!-- Bootstrap core JavaScript-->
<script src="~/vendor/jquery/jquery.min.js"></script>
<script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- Core plugin JavaScript-->
<script src="~/vendor/jquery-easing/jquery.easing.min.js"></script>
<!-- Page level plugin JavaScript-->
<script src="~/vendor/datatables/jquery.dataTables.js"></script>
<script src="~/vendor/datatables/dataTables.bootstrap4.js"></script>
<!-- Custom scripts for all pages-->
<script src="~/js/sb-admin.min.js"></script>
<!-- Custom scripts for this page-->
<script src="~/js/sb-admin-datatables.min.js"></script>